### PR TITLE
Offer translations #157 - Script + NL

### PR DESCRIPTION
**Pull request by joepio**
Toyed around a bit with translations #157. Not sure if this approach is the best.

Also, help is very much welcome!

- [x] Script that generate translations, iterates over all posts
- [x] Basic language configuration
- [x] Language routing
- [x] Language switcher
- [ ] Include other languages
  - [x] NL
- [ ] Translated non-post pages
  - [x] Home
- [ ] Translated components (footer, navbar)
- [ ] Versioning in translated files 
- [ ] AI generated notice

### CODE REVIEW

**Comment by anthonybailey** [comment]
Joep, I'm refining detail of a prompt myself. I've run a fair few
experiments. We should exchange notes.

I really want to pair on this stuff because in passing I'll learn a lot
about the design history of the website.

What do you think about my breakdown above: do you agree that most page
text content that is not in markdown (e.g. in .svelte, occasional fragments
in .ts, and some structured pieces) can be?

**Comment by joepio** [comment]
> do you agree that most page
text content that is not in markdown (e.g. in .svelte, occasional fragments
in .ts, and some structured pieces) can be?

@anthonybailey I don't think that's a good solution, at least for most of the items. I think we should have a bunch of json files.

**Comment by anthonybailey** [comment]
Right. So you want to plug the "standard" sveltekit i18n but power it from LLM. I get that. Do you have a proposal re exactly how routing will work?

I don't want to get in your way, but I have gone into the weeds re how to make the ongoing auto-LLM work, and I really do want to learn about the website from you.

The code Claude is accelerating may work but it is spaghetti and going to make maintenance hard. I can embrace the future but we should be factoring this stuff. Our new apprentice has a huge amount of energy but in September 2024 they need more design oversight.
Please can we arrange some time to work together on this?

**Comment by Reginred** [comment]
A fundamental problem with this approach is that pages using the search params [can't be prerendered](https://kit.svelte.dev/docs/page-options#prerender).

**Comment by joepio** [comment]
> @joepio Is there a specific reason why you added manual splitting of the path instead of using SvelteKits folder-based routing? The language could also be made an optional parameter to continue serving the English content under the current paths (and maybe redirecting from /en).

I think I used folder based routing in the last few commits. As in, use a `{lang}/{slug}` directory structure.

Maybe I'm bit understanding what you're saying / missing something!

**Comment by joepio** [comment]
I'm not planning on working on this PR anymore, this new one will be the one to watch: https://github.com/PauseAI/pauseai-website/pull/226

**Pull request closed without merging**
